---
language: java
jdk: openjdk8
sudo: required
dist: xenial
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - python
      - python-pip
      - docker-ce
stages:
#  - test
  - name: build
    if: branch = master || branch = release
env:
  global:
    - _JAVA_OPTIONS=-Xmx6g
    - TERM=dumb
    - HALE_GRADLE_CONSOLE=plain
#    - BINTRAY_PACKAGE=hale-dev  # TODO Make value depend on branch (master -> hale-dev, release -> hale)

jobs:
  include:
    - &build-hs 
      stage: build
      env:
        - PLATFORM=linux PLATFORM2=linux.gtk PRODUCT=HALE ARCH=x86_64 EXT=tar.gz
      before_deploy:
#        - ./generatebintraydesc.groovy -r ${BINTRAY_REPO} -p ${BINTRAY_PACKAGE} -s ${BINTRAY_USER} --buildNumber ${TRAVIS_BUILD_NUMBER} --branch ${TRAVIS_BRANCH} && cat .bintray.json
#        - echo "Deploying version $(<.version) to Bintray ${BINTRAY_USER}/${BINTRAY_REPO}/${BINTRAY_PACKAGE}"
        - echo "Deploying verion $(<.version) to AWS S3 bucket build-artifacts.wetransform.to"
#      deploy:
#        skip_cleanup: true
#        provider: bintray
#        file: .bintray.json
#        user: ${BINTRAY_USER}
#        key: ${BINTRAY_KEY}        
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: ${AWS_ACCESS_KEY}
        secret_access_key: ${AWS_SECRET_KEY}
        bucket: ${AWS_S3_BUCKET}
        region: ${AWS_S3_REGION}
        upload-dir: ${AWS_S3_BUCKET_TARGET_PATH}/${TRAVIS_BUILD_NUMBER}
        local_dir: build/target
# TEST
#      after_deploy:
#        - sleep 60
#        - |
#          BUILD_VERSION=$(<.version); curl --silent --show-error --fail\
#          -X PUT -H "Content-Type: application/json" -d'{"list_in_downloads": true}'\
#          -u$BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/file_metadata/${BINTRAY_USER}/${BINTRAY_REPO}/hale-studio-${BUILD_VERSION}-${PLATFORM2}.${ARCH}.${EXT}

      script:
        # Output something every miute lest Travis kills the job
        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
        - mkdir -p build/target
        - echo "3.5.0-SNAPSHOT" > build/.version.txt
        #- echo "test" > build/target/hale-studio-3.5.0.SNAPSHOT-${PLATFORM2}.${ARCH}.${EXT}
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./build.sh commitStage; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build.sh product -a ${ARCH} -o ${PLATFORM} ${PRODUCT}; fi'
        # Killing background sleep loop
        - kill %1
    - <<: *build-hs
      env:
        - PLATFORM=windows PLATFORM2=win32.win32 PRODUCT=HALE ARCH=x86_64 EXT=zip
    - <<: *build-hs
      env:
        - PLATFORM=macosx PLATFORM2=macosx.macosx PRODUCT=HALE ARCH=x86_64 EXT=tar.gz
      before_install:
        - sudo apt -qq update
        - sudo apt install -y genisoimage    
    - <<: *build-hs
      env:
        - PLATFORM=linux PLATFORM2=linux.gtk PRODUCT=HALE ARCH=x86 EXT=tar.gz
    - <<: *build-hs
      env:
        - PLATFORM=windows PLATFORM2=win32.win32 PRODUCT=HALE ARCH=x86 EXT=zip
    - <<: *build-hs
      env:
        - PLATFORM=macosx PLATFORM2=macosx.macosx PRODUCT=HALE ARCH=x86 EXT=tar.gz
      before_install:
        - sudo apt -qq update
        - sudo apt install -y genisoimage    
