---
language: java
jdk: oraclejdk8
sudo: required
dist: trusty
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - python
      - python-pip
      - docker-ce
stages:
#  - test
  - name: build
    if: branch = master || branch = release
env:
  global:
    - _JAVA_OPTIONS: -Xmx6g
    - WETF_ARTIFACTORY_USER: notarealuser
    - WETF_ARTIFACTORY_PASSWORD: notarealpassword
jobs:
  include:
#    - stage: test
#      if: type = pull_request
#      env:
#        - STAGE = commitStage
#      script:
#        # Output something every miute lest Travis kills the job
#        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
#        - HALE_GRADLE_CONSOLE=plain ./build.sh $STAGE
#        # Killing background sleep loop
#        - kill %1
#    - stage: test
#      if: branch = master
#      env:
#        - STAGE = integrationStage
#      script:
#        # Output something every miute lest Travis kills the job
#        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
#        - HALE_GRADLE_CONSOLE=plain ./build.sh $STAGE
#        # Killing background sleep loop
#        - kill %1
#    - stage: build
#      env:
#        - PLATFORM=macosx PRODUCT=HALE
#      before_install:
#        - sudo apt -qq update
#        - sudo apt install -y genisoimage
#      script:
#        # Output something every miute lest Travis kills the job
#        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
#        - HALE_GRADLE_CONSOLE=plain ./build.sh product -a x86_64 -o $PLATFORM $PRODUCT
#        # Killing background sleep loop
#        - kill %1
#    - stage: build
#      env:
#        - PLATFORM=windows PRODUCT=HALE
#      script:
#        # Output something every miute lest Travis kills the job
#        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
#        - HALE_GRADLE_CONSOLE=plain ./build.sh product -a x86_64 -o $PLATFORM $PRODUCT
#        # Killing background sleep loop
#        - kill %1
    - stage: build
      env:
        - PLATFORM=linux PRODUCT=HALE
      install:
        - sudo pip install --upgrade --force-reinstall pip==9.0.3
        - sudo pip install --progress-bar off awscli --disable-pip-version-check
      script:
        # Output something every miute lest Travis kills the job
        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
        - HALE_GRADLE_CONSOLE=plain ./build.sh product -a x86_64 -o $PLATFORM $PRODUCT
        - cd build && ./upload-site.sh
        - HALE_GRADLE_CONSOLE=plain ./build.sh deployArtifacts
        # Killing background sleep loop
        - kill %1
#    - stage: build
#      if: branch = master # should be 'branch = release'!
#      env:
#        - PLATFORM=linux PRODUCT=Infocenter
#      install:
#        - sudo pip install --upgrade pip
#        - sudo pip install --progress-bar off awscli
#      script:
#        # Output something every miute lest Travis kills the job
#        - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
#        - HALE_GRADLE_CONSOLE=plain ./build.sh product -a x86_64 -o $PLATFORM --publish --latest $PRODUCT
#        # Killing background sleep loop
#        - kill %1
