---
language: java
jdk: oraclejdk8
sudo: required
dist: trusty
script:
# Output something every miute lest Travis kills the job
  - while sleep 1m; do echo "=====[ $SECONDS seconds, still running... ]====="; done &
  - HALE_GRADLE_CONSOLE=plain ./build.sh commitStage
# Killing background sleep loop
  - kill %1
env:
  global:
    - _JAVA_OPTIONS: -Xmx6g
